name: CI

on:
  push:
  pull_request:
  create:

env:
  NODE_VERSION: 18

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: SetUpNode
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Runs a single command using the runners shell
      - name: Run echo event
        run: |
          echo "github.event_name ${{ github.event_name }}"

      - name: push event step
        if: github.event_name == 'push'
        run: |
          echo push event
      
      - name: pull request event step
        if: github.event_name == 'pull_request'
        run: |
          echo pull request event
      
      - name: create event step
        if: github.event_name == 'create'
        run: |
          echo create event
        

