name: CREATE-PR-TO-UPDATE-DEVELOP

on:
  pull_request:
    types:
      - closed

env:
  NODE_VERSION: 18
  BRANCH_NAME: ${{ github.ref_name }}
  GH_TOKEN: ${{ github.token }} # gh pr create に必要

jobs:
  create-pr-to-update-develop:

    if: github.event.pull_request.merged == true
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SetUpNode
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Update package version
        run: |

          : # gitにアカウント情報をセット
          echo "user - $GITHUB_ACTOR"
          echo "email - $GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email $GITHUB_ACTOR@users.noreply.github.com
          git config user.name
          git config user.email

          : # ブランチをmainから作成してチェックアウト
          NEW_BRANCH_NAME=feature/update-develop
          git switch -c $NEW_BRANCH_NAME main 

          : # ブランチをプッシュ
          git push origin $NEW_BRANCH_NAME

      - name: Create pull request
        run: |
          gh pr create \
            --base develop \
            --title "Update develop" \
            --body ""