name: GENERATE-DOCKER-IMAGE

on:
  workflow_dispatch:

jobs:
  generate-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: BuildImage
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          outputs: type=tar,dest=docker-image.tar
          push: false
          tags: "my-docker-image"
      
      - name: CheckFileList
        run: |
            ls -l

      - name: DockerInfo
        run: |
          docker info

      - name: DockerImages
        run: |
          docker images

      - name: DockerImportImage
        run: |
          docker import docker-image.tar my-docker-image:latest
        
      - name: DockerImages
        run: |
          docker images

      - name: DockerRunImage
        run: |
          docker run my-docker-image:latest echo "test"
      
      - name: UploadArtifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: ./docker-image.tar